### ISSUE TITLE
Uncaught exception: Error: Cannot create a string longer than 0x1fffffe8 characters

### ISSUE THREAD

**Issue by Nymerea** [jesec/flood#645] opened 2023-05-19 23:55 UTC
Type: Bug Report

- [ ] Try to follow the update procedure described in the README and try again before opening this issue.

## Your Environment

I'm on arch linux, i've installed flood. It was working well

## Summary

After a system restart, flood is unable to start with the folowing stack : 
```
npx flood
Flood server 4.7.0 starting on http://127.0.0.1:3000

(node:627) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
[Axios v4.7.0] Transitional option 'clarifyTimeoutError' has been deprecated since v1.0.0 and will be removed in the near future
[Axios v4.7.0] Transitional option 'forcedJSONParsing' has been deprecated since v1.0.0 and will be removed in the near future
[Axios v4.7.0] Transitional option 'silentJSONParsing' has been deprecated since v1.0.0 and will be removed in the near future
FATAL internal error. Please open an issue.
Uncaught exception: Error: Cannot create a string longer than 0x1fffffe8 characters
npm notice 
npm notice New major version of npm available! 8.19.2 -> 9.6.7
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.6.7
npm notice Run npm install -g npm@9.6.7 to update!
npm notice 
```

Look like I've reach the file limit of 500mb for a json. How that's possible ? Is there a way to clean it ?

**Comment by brndd** [comment] 2023-05-28 18:52
I am also hitting this problem after upgrading from Fedora 37 to 38.

**Comment by brndd** [comment] 2023-05-28 20:55
In my case the issue was that `/db/[randomstring]/history/fiveMinSnapshot.db` in the Flood config directory was about 700 MB in size. Removing that file solved the issue.

**Comment by dvdgsng** [comment] 2023-06-05 07:36
dupe of https://github.com/jesec/flood/issues/399

**Closed** 2024-12-17 18:44 UTC
