### ISSUE TITLE
Move torrent function broken in master

### ISSUE THREAD

**Issue by GitHubGeek** [jesec/flood#42] opened 2020-09-27 23:57 UTC
Type: Bug Report

- [x] Try to follow the update procedure described in the README and try again before opening this issue.
- [x] Please check the [F.A.Q.](https://github.com/Flood-UI/flood/wiki/F.A.Q.).
- [x] Please check the [Troubleshooting](https://github.com/Flood-UI/flood/wiki/Troubleshooting) wiki section.

## Your Environment

* Version used:
  + Commit ID (development release) `ab42dae2786c6c40835cf95cb64dbec7176a4dc8`
* Environment name and version:
  + Node.js version `v14.12.0`
  + npm version `6.14.8`
  + Web browser `Chrome 84`
* Operating System and version: `ubuntu 18.04`
* rTorrent version: `rTorrent-PS-CH 1.8.3 0.9.8/0.13.8`

## Summary

Set Torrent Location dialog moves torrents to an unexpected dir

## Expected Behavior

Torrents should be moved to the dir specified in the dialog

## Current Behavior

When moving torrents using the Set Torrent Location dialog, torrents were moved to `~/flood/undefined/` where `~/flood` is the src install dir 

## Steps to Reproduce

1. Install flood from src to `~/flood`, connect to existing rtorrent
2. Right click context menu > Set Torrent Location
3. Change path from `/foo/download` to `/foo/download2`, tick Move Data, click Set Location
4. Files being moved to `~/flood/undefined` instead of `/foo/download2`

**Comment by jesec** [comment] 2020-09-28 04:09
Resolved by https://github.com/jesec/flood/commit/d19f1485d6d44c4cf70f5efd6640a60ee3b18630. Please verify.

**Comment by GitHubGeek** [comment] 2020-09-29 01:13
Tested the function in the latest version. Data was moved to the right dir 👍 Thank you for the quick fix!

Side node: Ticked "Check Hash" in the dialog and got this in the terminal:

```
(node:31154) UnhandledPromiseRejectionWarning: TypeError: hashes.filter is not a function
    at ClientRequest.checkHash (/tank/rtorrent/flood/dist/index.js:121150:34)
    at ClientRequest.checkHash [as onCompleteFn] (/tank/rtorrent/flood/dist/index.js:121774:26)
    at ClientRequest.handleSuccess (/tank/rtorrent/flood/dist/index.js:121066:12)
    at /tank/rtorrent/flood/dist/index.js:121236:9
    at Array.forEach (<anonymous>)
    at ClientRequest.moveTorrents (/tank/rtorrent/flood/dist/index.js:121216:17)
    at ClientRequest.moveTorrents [as onCompleteFn] (/tank/rtorrent/flood/dist/index.js:121785:27)
    at ClientRequest.handleError (/tank/rtorrent/flood/dist/index.js:121052:12)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:31154) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:31154) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jesec** [comment] 2020-09-29 05:48
`moveTorrents` function has been refactored in 912c66d. Please verify if the issue is resolved.

**Comment by GitHubGeek** [comment] 2020-10-01 00:04
Tested on 7890ab74b5f578c563b77826fa3be89b591de526 - Set Torrent Location dialog works as expected. Thanks!

**Closed** 2020-10-21 01:19 UTC
