### ISSUE TITLE
manifest.json gets HTTP code 401 behind nginx reverse proxy with authentication

### ISSUE THREAD

**Issue by LeColonel31** [jesec/flood#339] opened 2021-06-25 08:34 UTC
Hey,

Just noticed this issue after upgrading from 4.5.4 to 4.6.0. It may not be flood related maybe just a Chromium thing but I just wanted to share as it may help other people.

## Environment

- Version used: 4.6.0
- Environment name and version:
  - Node.js version 14.17.1
  - npm version 7.19.0
  - Web browser Chromium v91
- Operating system and version: Debian 10.10
- Torrent client and version: rTorrent 0.9.8 (jesec version)

## Issue description

manifest.json gets a 401 HTTP error when behind an nginx reverse proxy with basic authentication.
This seems to break auto-refresh of the interface, for example traffic graph and transfer speed in torrents list are not updating.

Nginx configuration:
As described in wiki article.

## Expected Behavior

Auto refresh of graphs and transfer speed.

## Current Behavior

manifest.json gets HTTP 401 error and never loads whereas correct credentials have been provided.
Breaking auto refresh of web page (graphs, transfer speeds) and maybe other things I have not see.

## Possible Solution

Found this article:
[https://stackoverflow.com/questions/53527972/cant-get-rid-of-missing-manifest-json-error](url)

Modified /usr/lib/node_modules/flood/dist/assets/index.html :
`<link rel="manifest" href="manifest.json"/  >`
to
`<link rel="manifest" href="manifest.json"   crossorigin="use-credentials"/>`

## Steps to Reproduce

Behind nginx reverse proxy
Basic authentication
Chrome v91

Thank you so much for all the great work guys ! Flood is the best web interface for torrent clients !

**Comment by jesec** [comment] 2021-06-25 08:43
The manifest has nothing to do with the functionality of frontend.

If the data doesn't update, Flood frontend is probably unable to communicate with the backend due to some reasons.

**Comment by LeColonel31** [comment] 2021-06-25 09:01
You are right, restarting flood service solved the issue.

Anyway the provided solution allows to get rid of 401 errors on manifest.json.

**Comment by jesec** [comment] 2021-06-25 11:43
> You are right, restarting flood service solved the issue.
> 
> Anyway the provided solution allows to get rid of 401 errors on manifest.json.

Good to know. I am closing this for now since this is not a bug of Flood.

I will take a look at the manifest issue later.

**Closed by jesec** 2021-06-25 11:43 UTC
