### ISSUE TITLE
Remove Torrents -> Delete data: torrent directory not removed

### ISSUE THREAD

**Issue by r0bj** [jesec/flood#106] opened 2020-11-22 21:19 UTC
Type: Bug Report

- [x] Try to follow the update procedure described in the README and try again before opening this issue.
- [x] Please check the [F.A.Q.](https://github.com/Flood-UI/flood/wiki/F.A.Q.).
- [x] Please check the [Troubleshooting](https://github.com/Flood-UI/flood/wiki/Troubleshooting) wiki section.

## Your Environment

- Version used:
  - Version from docker (stable release) `v4.1.2`
- Environment name and version:
  - Web browser `chrome 87.0.4280.67 `

## Summary

Using `Remove Torrents` function with `Delete data` option marked deletes only torrent directory content, not directory itself.

## Expected Behavior

Using `Remove Torrents` function with `Delete data` option marked deletes torrent directory with its content.

## Steps to Reproduce

1. Add torrent `Fedora-Workstation-Live-x86_64-33`
```
# tree Fedora-Workstation-Live-x86_64-33/
Fedora-Workstation-Live-x86_64-33/
├── Fedora-Workstation-33-1.2-x86_64-CHECKSUM
└── Fedora-Workstation-Live-x86_64-33-1.2.iso
```
```
# ls -lan Fedora-Workstation-Live-x86_64-33/
total 2001484
drwxrws---+  2 3000 3000       4096 Nov 22 11:29 .
drwxrws---+ 86 3000 3000      12288 Nov 22 11:29 ..
-rw-rw----+  1 3000 3000       1062 Nov 22 11:30 Fedora-Workstation-33-1.2-x86_64-CHECKSUM
-rw-rw----+  1 3000 3000 2049490944 Nov 22 11:32 Fedora-Workstation-Live-x86_64-33-1.2.iso
```
2. Remove Torrents -> Delete data
```
# tree Fedora-Workstation-Live-x86_64-33/
Fedora-Workstation-Live-x86_64-33/
```
```
# ls -lan Fedora-Workstation-Live-x86_64-33/
total 20
drwxrws---+  2 3000 3000  4096 Nov 22 13:14 .
drwxrws---+ 86 3000 3000 12288 Nov 22 13:14 ..
```
Note: torrent directory content is removed while directory remains present

floood logs:
```
POST /api/torrents/delete 200 374.208 ms - -
PATCH /api/settings 200 3.538 ms - 26
```

Parent directory permissions allows flood to r/w access (flood is running with UID/GID 3000):
```
# ls -land downloads/
drwxrws---+ 86 3000 3000 12288 Nov 22 13:14 downloads/
```

**Comment by jesec** [comment] 2020-11-23 02:05
See #13, #25 and #35.

**Comment by bbashy** [comment] 2020-11-23 02:25
Use your `.rtorrent.rc` to control this?

```
# Delete whole folder/path when removing torrents.
method.set_key = event.download.erased, delete_erased, "execute=rm,-rf,--,$d.data_path="
```

**Comment by r0bj** [comment] 2020-11-23 03:02
As far as I understand comment https://github.com/jesec/flood/issues/25 leaving (not deleting) torrent base directory is intentional?

Correct me if I'm wrong, desired flood workflow looks like:
1. add torrent containing multiple files so it has its own base directory A_TORRENT
2. after content is consumed I would like to delete everything what's related to this torrent
3. `Remove Torrents` -> `Delete data` deletes all files except directory A_TORRENT
4. directory A_TORRENT stays forever on the filesystem unless manually deleted outside of flood

Is this how the flood workflow should look like?

I'm coming directly from flood https://github.com/Flood-UI/flood/releases/tag/v1.0.0 where deleting directory A_TORRENT worked, so that's where my surprise comes from.

**Comment by jesec** [comment] 2020-11-23 05:49
Are you sure that you came from the 1.0 release? It was released in 2017. 

Yes. It is the intended behavior at the moment. When it comes to permanent data deletion, it is better safe than sorry.

**Comment by r0bj** [comment] 2020-11-23 06:24
> Are you sure that you came from the 1.0 release? It was released in 2017.

Yeah, I was waiting for the new release too long :)

> Yes. It is the intended behavior at the moment. When it comes to permanent data deletion, it is better safe than sorry.

Thanks for info, feel free to close this issue then.

**Closed** 2020-11-23 11:02 UTC
