### ISSUE TITLE
Connection could not be verified. - qBittorrent v4.5.0 Web UI (64-bit)

### ISSUE THREAD

**Issue by TheFatPanda-Dev** [jesec/flood#629] opened 2023-01-27 18:02 UTC
### Discussed in https://github.com/jesec/flood/discussions/628

<div type='discussions-op-text'>

<sup>Originally posted by **IamTheKingKong** January 27, 2023</sup>
I run Flood on the same docker network (Synology server) as qBittorrent but for some reason, I can't connect to it.
I've tried all localhost IPs but still nothing.

Any ideas?

![not working](https://user-images.githubusercontent.com/46047869/215156582-05684e4b-43eb-4999-bb04-4cf7d9a86263.png)
</div>

**Comment by ggonmar** [comment] 2023-02-14 18:47
Same here

**Comment by happyeddie** [comment] 2023-02-20 05:04
+1

**Comment by mrnetlex** [comment] 2023-02-25 00:39
+1

**Comment by Goooooooooood** [comment] 2023-03-02 07:37
+1

**Comment by Ojasv24** [comment] 2023-03-06 10:52
+1

**Comment by ThatIcyPolarBear** [comment] 2023-03-08 12:49
+1

**Comment by ddnomad** [comment] 2023-03-13 22:41
+1

**Comment by agneevX** [comment] 2023-03-27 17:36
Compiling from master works with the latest qBittorrent release, or deploy `jesec/flood:master`.

**Comment by brezinajn** [comment] 2023-03-28 13:29
> Compiling from master works with the latest qBittorrent release, or deploy `jesec/flood:master`.

The issue is some downstream consumers deploy only based on stable releases, so this is not a universal solution. Unfortunately it seems this project became unmaintained. So I don't see this being resolved in the near future.

**Comment by enoch85** [comment] 2023-04-05 15:27
Does anyone have the latest nightly? It was [here](https://nightly.link/jesec/flood/workflows/publish-rolling/master/flood-linux-x64) before, but not available anymore.

**Comment by AurimasNav** [comment] 2023-05-28 17:05
same issue, since this does not seem to be fixed anytime soon, any recommendations for another webui for qbittorrent?

**Comment by vvirtues** [comment] 2023-06-06 11:09
using WSL for @enoch85 's release works perfectly for me. It's a shame this repo is inactive, i love the UI compared to vuetorrent

**Comment by vp-en** [comment] 2023-08-06 16:14
I created a "nightly" Docker image fork of hotio's that automatically updates flood with each push to the master branch. It's a minor change to the original image.

It basically takes the most recent successful run of [this workflow](https://github.com/jesec/flood/actions/workflows/publish-rolling.yml), grabs the id, forwards it to the Dockerfile, and then downloads the release from that run.

Simple, but effective, and it should be automatically updated with the upstream flood and qbittorrent.

**Link:**
https://github.com/vp-en/qflood

**Comment by disconn3ct** [comment] 2023-08-07 14:45
FYI 'jesec/flood:master-distroless' works fine. No need for a bundle with qbit or anything.

https://hub.docker.com/r/jesec/flood/tags

**Comment by engels74** [comment] 2024-01-27 00:09
> I created a "nightly" Docker image fork of hotio's **rflood** image, that automatically updates flood with each push to the master branch. It's a minor change to the original image.
> 
> It basically takes the most recent successful run of [this workflow](https://github.com/jesec/flood/actions/workflows/publish-rolling.yml), grabs the id, forwards it to the Dockerfile, and then downloads the release from that run.
> 
> Simple, but effective, and it should be automatically updated with the upstream flood and qbittorrent.
> 
> **Link:** https://github.com/vp-en/qflood

Moved it to https://github.com/engels74/qflood

**Comment by trim21** [comment] 2024-04-25 20:54
just make a new release.

**Closed** 2024-04-26 00:01 UTC
